
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import jade.Window;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world");

        Window window = Window.get();
        window.run();
    }
}
